#!/bin/sh

. /usr/share/libubox/jshn.sh

case "$1" in
	list)
		json_init

       	json_add_object "get_installed_pkgs"
       	json_close_object
       	json_add_object "sysupgrade"
       	json_close_object

       	json_dump
        ;;
    call)
        case "$2" in
            get_installed_pkgs)
        	    json_init;
                json_add_object "installed_pkgs"

                if [ -f /usr/lib/opkg/status ]; then

                    while read var p1 p2 p3; do
                        if [ "$var" = "Package:" ]; then
                            pkg="$p1"
                        fi

                        if [ "$var" = "Version:" ]; then
                            version="$p1"
                        fi

                        if [ "$var" = "Status:" \
                            -a "$p1" = "install" \
                            -a "$p2" = "user" -a "$p3" = "installed" ]; then
                                    json_add_string "$pkg" "$version";
                        fi
                    done < /usr/lib/opkg/status
                fi

                json_close_object
                json_dump
            ;;
			sysupgrade)
				if [ -f "/tmp/sysupgrade.bin" ]; then
					/etc/init.d/uhttpd stop
					/etc/init.d/dropbear stop
					sleep 1;
					/sbin/sysupgrade -c /tmp/sysupgrade.bin
				fi
				json_init
				json_add_string "message" "could not find /tmp/sysupgrade.bin"
				json_dump
        esac
    ;;
esac

