- name: ensure database is created
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ db_name }}"

- name: ensure user has access to database
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: ALL

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
    name: "{{ db_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB
