- name: include vars
  include_vars: "{{ playbook_dir }}/{{ config_file }}"
- name: install required software
  package: name={{ item }} state=present
  with_items:
    - git
    - nginx
    - nginx-extras # required for fancyindex
    - postgresql
    - odbc-postgresql
    - unixodbc-dev
    - python3-psycopg2
    - python-psycopg2
    - python3-yaml
    - python3-flask
    - python3-pip

- pip:
    executable : pip3
    name: pyodbc

- name: install imagebuilder dependencies
  package: name={{ item }} state=present
  with_items:
    - time
    - subversion
    - build-essential
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc
    - wget
    - unzip
    - python

- name: clone server git repo
  become_user: "{{ server_user }}"
  git:
    repo: 'https://github.com/aparcar/attendedsysupgrade-server.git'
    dest: "{{ server_dir }}"
    version: "{{ git_branch | default('master') }}"
  when: server_dir != "/vagrant"

- name: copy server service
  template:
    src: asu-server.service
    dest: /etc/systemd/system/asu-server.service

- name: copy config file
  become_user: "{{ server_user }}"
  template: src="{{ playbook_dir }}/{{ config_file }}" dest="{{ server_dir }}/config.yml"

- name: setup database
  include: postgres.yml

- name: start and enable server
  service:
    name: asu-server
    state: started
    enabled: true

- name: init server
  become_user: "{{ server_user }}"
  command: python3 cli.py -r # init server
  args:
    chdir: "{{ server_dir }}"

- name: copy nginx config
  template:
      src: asu-server.conf
      dest: /etc/nginx/sites-available/default
  notify:
      - nginx reload

