---
- name: 'Install Packages'
  package:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'nginx'
    - 'postgresql'
    - 'odbc-postgresql'
    - 'python3-pyodbc'
    - 'python3-psycopg2'
    - 'python3-gnupg'
    - 'python-psycopg2'
    - 'python3-yaml'
    - 'python3-flask'
    - 'git'
    - 'subversion'
    - 'build-essential'
    - 'libncurses5-dev'
    - 'zlib1g-dev'
    - 'gawk'
    - 'git'
    - 'ccache'
    - 'gettext'
    - 'libssl-dev'
    - 'xsltproc'
    - 'wget'
    - 'unzip'
    - 'python'

- name: 'Clone Repository'
  git:
    repo: 'https://github.com/aparcar/gsoc17-attended-sysupgrade.git'
    dest: '{{ server_folder }}'
    update: '{{ force_update }}'
  notify:
    - 'Restart Server'

- name: 'Ensure Database'
  become_user: 'postgres'
  postgresql_db:
    name: '{{ database_name }}'

- name: 'Ensure Database Access'
  become_user: 'postgres'
  postgresql_user:
    db: '{{ database_name }}'
    name: '{{ database_user }}'
    password: '{{ database_pass }}'
    priv: 'ALL'

- name: 'Ensure User Priveleges'
  become_user: 'postgres'
  postgresql_user:
    name: '{{ database_user }}'
    role_attr_flags: 'NOSUPERUSER,NOCREATEDB'

- name: 'Template nginx Configuration'
  template:
    src: 'server.conf.j2'
    dest: '/etc/nginx/sites-enabled/server.conf'

- name: 'Template Service'
  template:
    src: 'server.service.j2'
    dest: '/etc/systemd/system/server.service'

# This stanza is referencing a missing file.
- name: 'Template Configuration'
  template:
    src: 'config.yml.j2'
    dest: '{{ server_folder }}/config.yml'

- name: 'Ensure Server Service Started/Enabled'
  service:
    name: 'server'
    state: 'started'
    enabled: True

# This stanza is NOT IDEMPOTENT. Perhaps reference a 'creates' to prevent undesirable repetition.
# download all releases and init all current imagebuilders
- name: 'Initialize Server'
  become_user: '{{ server_user }}'
  command: 'python3 cli.py -ia'
  args:
    chdir: '{{ server_folder }}'

