language: python

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - odbc-postgresql
    - unixodbc-dev

python:
  - "3.6"

install:
  - pip install flake8 pytest coverage "pytest-cov<2.6.0" codacy-coverage

before_script:
  - psql -c "create database asu;" -U postgres
  - psql -c "create role asu with password 'changeme' nosuperuser nocreatedb nocreaterole noinherit login;" -U postgres
  - psql -c "grant all privileges on database asu to asu;" -U postgres
  - psql asu < ./asu/utils/tables.sql -U postgres
  - cp ./contrib/odbc.ini ~/.odbc.ini

script:
  - pip install -e .
  - flake8 --exclude=asu/__init__.py --max-line-length=88
  - pytest -c pytest.ini --cov=asu
  - python3 -m coverage xml
  - python3 -m codacy -r coverage.xml
