FROM python:3.7-buster

RUN useradd -c "OpenWrt Builder" -m -d /home/build -s /bin/bash build

USER build

RUN mkdir /home/build/asu/

WORKDIR /home/build/asu/

COPY ./misc/config.py /etc/asu/config.py

RUN pip install --no-cache-dir gunicorn asu

ENV PATH="/home/build/.local/bin:${PATH}"

CMD /bin/sh -c 'gunicorn "asu.asu:create_app()" --bind 0.0.0.0:8000'

EXPOSE 8000
