version: "2"

volumes:
  redis:

services:
  server:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    environment:
      - REDIS_URL=redis://redis/
      - ALLOW_DEFAULTS
      - PUBLIC_PATH
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis

  worker:
    image: "asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    restart: always
    command: rqworker --with-scheduler
    environment:
      - CONTAINER_HOST=unix://$CONTAINER_SOCK
      - REDIS_URL=redis://redis/
    volumes:
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
      - $CONTAINER_SOCK:$CONTAINER_SOCK:rw
    depends_on:
      - redis

  # worker2:
  #   image: "asu:latest"
  #   build:
  #     context: ./
  #     dockerfile: Containerfile
  #   restart: always
  #   command: rqworker --with-scheduler
  #   environment:
  #     - CONTAINER_HOST=unix://$CONTAINER_SOCK
  #     - REDIS_URL=redis://redis/
  #   volumes:
  #     - $PUBLIC_PATH:$PUBLIC_PATH:rw
  #     - $CONTAINER_SOCK:$CONTAINER_SOCK:rw
  #   depends_on:
  #     - redis

  redis:
    image: "docker.io/redis:alpine"
    restart: always
    volumes:
      - redis:/data/:rw
