version: "2"
volumes:
  podman-sock:
  redis:
services:
  server:
    image: "localhost/aparcar/asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    environment:
      - REDIS_URL=redis://redis/
    volumes:
      - "./asu-service/public/:/app/public/:rw"
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - redis

  worker:
    image: "localhost/aparcar/asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    command: rqworker --url "redis://redis"
    environment:
      - CONTAINER_HOST=unix:///tmp/socket/podman.sock
      - REDIS_URL=redis://redis/
    volumes:
      - ./asu-service/public/:/app/public/:rw
      - podman-sock:/tmp/socket/:rw
    depends_on:
      - redis
      - podman

  worker2:
    image: "localhost/aparcar/asu:latest"
    build:
      context: ./
      dockerfile: Containerfile
    command: rqworker --url "redis://redis"
    environment:
      - CONTAINER_HOST=unix:///tmp/socket/podman.sock
      - REDIS_URL=redis://redis/
    volumes:
      - ./asu-service/public/:/app/public/:rw
      - podman-sock:/tmp/socket/:rw
    depends_on:
      - redis
      - podman

  podman:
    image: quay.io/podman/stable
    user: podman
    volumes:
      - podman-sock:/tmp/socket/
    command: sh -c "mkdir -p /tmp/socket && podman system service --time=0 unix:///tmp/socket/podman.sock"

  redis:
    image: "docker.io/redis:alpine"
    volumes:
      - redis:/data/:rw

# Podman may not allow ports 1024, consider using an external web server
# webserver:
#   image: caddy
#   volumes:
#     - "./misc/Caddyfile:/etc/caddy/Caddyfile"
#     - "./asu-service:/site/"
#   ports:
#     - "8000:8081"
#   depends_on:
#     - server
