# user to login
ansible_user: root
# where to find the server
ansible_host: example.org
# which branch of asu to install
# if emtpy or unset, use pip3
git_branch: master
# user to run asu
server_user: asu
# domain for nginx to listen on
nginx_url: asu.example.org
# where to find config.yml
config_folder: /etc/asu/
# database user
db_user: asu
# database name
db_name: asu
# database password
db_pass: changeme
