---
distro_alias: OpenWrt
latest: "18.06.1"
versions:
  - 18.06.1
  - 18.06.0
  - snapshots
vanilla:
  - luci
targets_url: https://downloads.openwrt.org/releases/
board_rename:
  nanostation-m: ubnt-nano-m
  nanostation-m-xw: ubnt-nano-m-xw
  loco-m: ubnt-loco-m
  loco-m-xw: ubnt-loco-m-xw
  tl-wdr3500: tl-wdr3500-v1
  tl-wdr4300: tl-wdr4300-v1
  tl-wr741: tl-wr741-v1
  raspberrypi,3-model-b: rpi-3
  armada-385-linksys-rango: linksys-wrt3200acm
