
image:
	cp ./openwrt-testtarget-testsubtarget-testprofile-sysupgrade.bin $(BIN_DIR)/
	cp ./openwrt-testtarget-testsubtarget-testprofile.json $(BIN_DIR)/
	cp ./openwrt-testtarget-testsubtarget-testprofile.manifest $(BIN_DIR)/

manifest:
	@cat ./openwrt-testtarget-testsubtarget-testprofile.manifest

info:
	@cat ./openwrt-testtarget-testsubtarget-testprofile.info
