#!/bin/sh

. /usr/share/libubox/jshn.sh

case "$1" in
        list)
                json_init

                json_add_object "get_installed_pkgs"
                json_close_object
                json_add_object "get_board"
                json_close_object

                json_dump
        ;;
        call)
                case "$2" in
                        get_installed_pkgs)
                                json_init;
                                json_add_object "installed_pkgs"

                                if [ -f /usr/lib/opkg/status ]; then

                                        while read var p1 p2 p3; do
                                                if [ "$var" = "Package:" ]; then
                                                        pkg="$p1"
                                                fi

                                                if [ "$var" = "Version:" ]; then
                                                        version="$p1"
                                                fi

                                                if [ "$var" = "Status:" \
                                                        -a "$p1" = "install" \
                                                        -a "$p2" = "user" -a "$p3" = "installed" ]; then
                                                                json_add_string "$pkg" "$version";
                                                fi
                                        done < /usr/lib/opkg/status
                                fi

                                json_close_object
                                json_dump
                        ;;
                        get_board)
                                json_init

								# best approach but only works on few devices
								board="$(cat sys/firmware/devicetree/base/model)"

								if [ -z "$board" ]; then
									# can result in useless board names on x86
									board=$(cat /tmp/sysinfo/board_name)
								fi

								if [ -z "$board" ]; then
									json_add_string "board" "$board"
								if

								# fall back method
                                machine=$(grep machine /proc/cpuinfo | awk '{print $2}')
								if [ -z "$board" ]; then
									json_add_string "machine" "$machine"
								if

                                json_dump
                esac
        ;;
esac

