---
- hosts: 'server'
  become: True
  become_method: 'sudo'
  roles:
    - { role: 'asysup-server' }

- hosts: 'workers'
  become: True
  become_method: 'sudo'
  roles:
    - { role: 'asysup-worker' }
