---
# an alias for the distribution to beautify user interfaces
distro_alias: OpenWrt

# latest release available, used for responses to upgrade requests
latest: "snapshot"

# a list of all active versions
versions:
  - snapshot

version_common:
    # additional packages to be installed per default
    vanilla:
      - luci

    # url to imagebuilders
    targets_url: https://downloads.openwrt.org/releases/{version}/targets?json-targets
