---
# an alias for the distribution to beautify user interfaces
distro_alias: OpenWrt

# latest release available, used for responses to upgrade requests
latest: "18.06.4"

# a list of all active versions
versions:
  - 18.06.4
  - 18.06.3
  - 18.06.2
  - 18.06.1
  - 18.06.0
  - snapshot

version_common:
    # additional packages to be installed per default
    vanilla:
      - luci

    # url to imagebuilders
    targets_url: https://downloads.openwrt.org/releases/{version}/targets?json-targets
